pub fn SumOfProductsGen(comptime T: type) type {
    return struct {
        pub fn sum(items: []const T, r: usize) T {
            var s: T = 0;
            const l0: usize = items.len;
            const p0: T = 1;

            if (r == l0) {
                var p: T = 1;
                var l1: usize = 0;
                while (l1 < l0) : (l1 += 1) {
                    p *= items[l1];
                }
                return p;
            }

            switch (r) {
                1 => {
                    var l1: usize = 0;
                    while (l1 < l0) : (l1 += 1) {
                        s += items[l1];
                    }
                },

                // generated by gen.rb
                2 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2 = p1 * items[l2];
                            s += p2;
                        }
                    }
                },
                3 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3 = p2 * items[l3];
                                s += p3;
                            }
                        }
                    }
                },
                4 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4 = p3 * items[l4];
                                    s += p4;
                                }
                            }
                        }
                    }
                },
                5 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5 = p4 * items[l5];
                                        s += p5;
                                    }
                                }
                            }
                        }
                    }
                },
                6 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6 = p5 * items[l6];
                                            s += p6;
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                7 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7 = p6 * items[l7];
                                                s += p7;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                8 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8 = p7 * items[l8];
                                                    s += p8;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                9 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9 = p8 * items[l9];
                                                        s += p9;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                10 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10 = p9 * items[l10];
                                                            s += p10;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                11 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11 = p10 * items[l11];
                                                                s += p11;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                12 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12 = p11 * items[l12];
                                                                    s += p12;
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                13 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13 = p12 * items[l13];
                                                                        s += p13;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                14 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14 = p13 * items[l14];
                                                                            s += p14;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                15 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15 = p14 * items[l15];
                                                                                s += p15;
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                16 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15: T = p14 * items[l15];

                                                                                var l16: usize = r - 16;
                                                                                while (l16 < l15) : (l16 += 1) {
                                                                                    var p16 = p15 * items[l16];
                                                                                    s += p16;
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                17 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15: T = p14 * items[l15];

                                                                                var l16: usize = r - 16;
                                                                                while (l16 < l15) : (l16 += 1) {
                                                                                    var p16: T = p15 * items[l16];

                                                                                    var l17: usize = r - 17;
                                                                                    while (l17 < l16) : (l17 += 1) {
                                                                                        var p17 = p16 * items[l17];
                                                                                        s += p17;
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                18 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15: T = p14 * items[l15];

                                                                                var l16: usize = r - 16;
                                                                                while (l16 < l15) : (l16 += 1) {
                                                                                    var p16: T = p15 * items[l16];

                                                                                    var l17: usize = r - 17;
                                                                                    while (l17 < l16) : (l17 += 1) {
                                                                                        var p17: T = p16 * items[l17];

                                                                                        var l18: usize = r - 18;
                                                                                        while (l18 < l17) : (l18 += 1) {
                                                                                            var p18 = p17 * items[l18];
                                                                                            s += p18;
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                19 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15: T = p14 * items[l15];

                                                                                var l16: usize = r - 16;
                                                                                while (l16 < l15) : (l16 += 1) {
                                                                                    var p16: T = p15 * items[l16];

                                                                                    var l17: usize = r - 17;
                                                                                    while (l17 < l16) : (l17 += 1) {
                                                                                        var p17: T = p16 * items[l17];

                                                                                        var l18: usize = r - 18;
                                                                                        while (l18 < l17) : (l18 += 1) {
                                                                                            var p18: T = p17 * items[l18];

                                                                                            var l19: usize = r - 19;
                                                                                            while (l19 < l18) : (l19 += 1) {
                                                                                                var p19 = p18 * items[l19];
                                                                                                s += p19;
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                20 => {
                    var l1: usize = r - 1;
                    while (l1 < l0) : (l1 += 1) {
                        var p1: T = p0 * items[l1];

                        var l2: usize = r - 2;
                        while (l2 < l1) : (l2 += 1) {
                            var p2: T = p1 * items[l2];

                            var l3: usize = r - 3;
                            while (l3 < l2) : (l3 += 1) {
                                var p3: T = p2 * items[l3];

                                var l4: usize = r - 4;
                                while (l4 < l3) : (l4 += 1) {
                                    var p4: T = p3 * items[l4];

                                    var l5: usize = r - 5;
                                    while (l5 < l4) : (l5 += 1) {
                                        var p5: T = p4 * items[l5];

                                        var l6: usize = r - 6;
                                        while (l6 < l5) : (l6 += 1) {
                                            var p6: T = p5 * items[l6];

                                            var l7: usize = r - 7;
                                            while (l7 < l6) : (l7 += 1) {
                                                var p7: T = p6 * items[l7];

                                                var l8: usize = r - 8;
                                                while (l8 < l7) : (l8 += 1) {
                                                    var p8: T = p7 * items[l8];

                                                    var l9: usize = r - 9;
                                                    while (l9 < l8) : (l9 += 1) {
                                                        var p9: T = p8 * items[l9];

                                                        var l10: usize = r - 10;
                                                        while (l10 < l9) : (l10 += 1) {
                                                            var p10: T = p9 * items[l10];

                                                            var l11: usize = r - 11;
                                                            while (l11 < l10) : (l11 += 1) {
                                                                var p11: T = p10 * items[l11];

                                                                var l12: usize = r - 12;
                                                                while (l12 < l11) : (l12 += 1) {
                                                                    var p12: T = p11 * items[l12];

                                                                    var l13: usize = r - 13;
                                                                    while (l13 < l12) : (l13 += 1) {
                                                                        var p13: T = p12 * items[l13];

                                                                        var l14: usize = r - 14;
                                                                        while (l14 < l13) : (l14 += 1) {
                                                                            var p14: T = p13 * items[l14];

                                                                            var l15: usize = r - 15;
                                                                            while (l15 < l14) : (l15 += 1) {
                                                                                var p15: T = p14 * items[l15];

                                                                                var l16: usize = r - 16;
                                                                                while (l16 < l15) : (l16 += 1) {
                                                                                    var p16: T = p15 * items[l16];

                                                                                    var l17: usize = r - 17;
                                                                                    while (l17 < l16) : (l17 += 1) {
                                                                                        var p17: T = p16 * items[l17];

                                                                                        var l18: usize = r - 18;
                                                                                        while (l18 < l17) : (l18 += 1) {
                                                                                            var p18: T = p17 * items[l18];

                                                                                            var l19: usize = r - 19;
                                                                                            while (l19 < l18) : (l19 += 1) {
                                                                                                var p19: T = p18 * items[l19];

                                                                                                var l20: usize = r - 20;
                                                                                                while (l20 < l19) : (l20 += 1) {
                                                                                                    var p20 = p19 * items[l20];
                                                                                                    s += p20;
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                // generated by gen.rb

                else => unreachable,
            }
            return s;
        }
    };
}
